language: php

sudo: false

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

branches:
  only:
    - master

matrix:
  allow_failures:
    - php: '5.5'

install:
  - composer install -n --dev

script:
  - bin/atoum -f test.php
